language: julia
os:
  - linux

dist: xenial

julia:
  - 1.0.1

notifications:
  email: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/python-3.6'
    packages:
      - "python3.6"

before_install:
  - sudo apt-get update
  - curl https://bootstrap.pypa.io/get-pip.py | sudo -H python3.6
  - sudo pip3 install sympy

#install:

#script:
  #- julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("$pkgname"); Pkg.test("$pkgname"; coverage=false)'
