language: julia
os:
  - linux

dist: xenial

julia:
  - 1.0.1

python:
  - "3.6"

notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get install python3-pip
  - pip3 install --user sympy

#install:

#script:
  #- julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("$pkgname"); Pkg.test("$pkgname"; coverage=false)'
